name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generiere README.md
        run: ./generate_readme.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: Wim Wenigerkind
          commit_user_email: wim.wenigerkind@heptacom.de
          commit_author: Wim Wenigerkind <wim.wenigerkind@heptacom.de>